/*
 * This source file was generated by the Gradle 'init' task
 */
package jarQuery

import java.time.LocalDateTime
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AppTest {
    @Test fun appHasAGreeting() {
        val now = ZonedDateTime.now()
        println("now: ${now}")
        val dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm z")
        println("formatted: ${dtf.format(now)}")
        assertTrue(true)
    }
}
